// <auto-generated />
using System;
using KaraokePayment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KaraokePayment.Data.Migrations
{
    [DbContext(typeof(KaraokeDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KaraokePayment.Data.Entity.BookPhongOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KhachHangId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NhanVienCaLVId")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NhanVienCaLVId");

                    b.ToTable("BookPhongOrder");
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.BookPhongOrderPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookPhongOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienBook1Id")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienBook2Id")
                        .HasColumnType("int");

                    b.Property<int>("PhongId")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucTT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookPhongOrderId");

                    b.HasIndex("PhongId");

                    b.ToTable("BookPhongOrderPhong");
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.CaLV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Den")
                        .HasColumnType("float");

                    b.Property<double>("HeSoLuong")
                        .HasColumnType("float");

                    b.Property<string>("TenCa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Tu")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CaLV");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Den = 11.0,
                            HeSoLuong = 1.0,
                            TenCa = "Ca 1",
                            Tu = 7.0
                        },
                        new
                        {
                            Id = 2,
                            Den = 18.0,
                            HeSoLuong = 1.0,
                            TenCa = "Ca 2",
                            Tu = 11.0
                        },
                        new
                        {
                            Id = 3,
                            Den = 22.0,
                            HeSoLuong = 1.5,
                            TenCa = "Ca 3",
                            Tu = 18.0
                        },
                        new
                        {
                            Id = 4,
                            Den = 2.0,
                            HeSoLuong = 2.0,
                            TenCa = "Ca 4",
                            Tu = 22.0
                        });
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.DiaChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tinh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaChi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Huyen = "Nam Sach",
                            Tinh = "Hai Duong"
                        },
                        new
                        {
                            Id = 2,
                            Huyen = "Tan Trieu",
                            Tinh = "Ha Noi"
                        },
                        new
                        {
                            Id = 3,
                            Huyen = "Ha Dong",
                            Tinh = "Ha Noi"
                        },
                        new
                        {
                            Id = 4,
                            Huyen = "Nam Tan",
                            Tinh = "Hai Duong"
                        },
                        new
                        {
                            Id = 5,
                            Huyen = "Cam Giang",
                            Tinh = "Hai Duong"
                        });
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.HangHoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaHH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HangHoa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gia = 10000m,
                            HanSuDung = new DateTime(2022, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaHH = "HH001",
                            NgayNhap = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuong = 50,
                            Ten = "Bim Bim Oshi Cay"
                        },
                        new
                        {
                            Id = 2,
                            Gia = 20000m,
                            HanSuDung = new DateTime(2022, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaHH = "HH002",
                            NgayNhap = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuong = 50,
                            Ten = "Dia Hoa Qua"
                        },
                        new
                        {
                            Id = 3,
                            Gia = 20000m,
                            HanSuDung = new DateTime(2022, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaHH = "HH003",
                            NgayNhap = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuong = 50,
                            Ten = "Bim Bim Ostar"
                        },
                        new
                        {
                            Id = 4,
                            Gia = 40000m,
                            HanSuDung = new DateTime(2022, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaHH = "HH004",
                            NgayNhap = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuong = 1000,
                            Ten = "Bia Sai Gon"
                        },
                        new
                        {
                            Id = 5,
                            Gia = 45000m,
                            HanSuDung = new DateTime(2022, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaHH = "HH005",
                            NgayNhap = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuong = 1000,
                            Ten = "Bia Heineken"
                        });
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.NhanVienCaLV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CaLvId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLV")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CaLvId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("NhanVienCaLV");
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.Phong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoPhong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsVIP")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Phong");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoPhong = "small",
                            Gia = 150000m,
                            IsVIP = false,
                            TenPhong = "P 101",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 2,
                            CoPhong = "small",
                            Gia = 300000m,
                            IsVIP = true,
                            TenPhong = "P 102",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 3,
                            CoPhong = "small",
                            Gia = 150000m,
                            IsVIP = false,
                            TenPhong = "P 103",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 4,
                            CoPhong = "medium",
                            Gia = 300000m,
                            IsVIP = false,
                            TenPhong = "P 201",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 5,
                            CoPhong = "medium",
                            Gia = 600000m,
                            IsVIP = true,
                            TenPhong = "P 202",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 6,
                            CoPhong = "medium",
                            Gia = 300000m,
                            IsVIP = false,
                            TenPhong = "P 203",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 7,
                            CoPhong = "big",
                            Gia = 600000m,
                            IsVIP = false,
                            TenPhong = "P 301",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 8,
                            CoPhong = "big",
                            Gia = 1200000m,
                            IsVIP = true,
                            TenPhong = "P 302",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 9,
                            CoPhong = "big",
                            Gia = 600000m,
                            IsVIP = false,
                            TenPhong = "P 303",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.ThemHangHoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookPhongOrderPhongId")
                        .HasColumnType("int");

                    b.Property<int>("HangHoaId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookPhongOrderPhongId");

                    b.HasIndex("HangHoaId");

                    b.ToTable("ThemHangHoa");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.KhachHang", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("CMT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiaChiId")
                        .HasColumnType("int");

                    b.Property<string>("Ho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVIP")
                        .HasColumnType("bit");

                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("DiaChiId");

                    b.HasDiscriminator().HasValue("KhachHang");

                    b.HasData(
                        new
                        {
                            Id = "fa123bb7-10ce-454a-9408-7ef57dd8f131",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "12e5fd36-3ba0-4ced-a11b-7819fec565be",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "df6aaddf-81d5-4fab-a38e-585a87a2852f",
                            TwoFactorEnabled = false,
                            Ho = "Ngo Ba",
                            IsVIP = true,
                            MaKH = "KH001",
                            NgaySinh = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0665324444",
                            Ten = "Hung"
                        },
                        new
                        {
                            Id = "a7a7feea-f4dc-4de7-a0ea-2ad1ca46713b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "64c7bc5a-d4c8-4789-a439-2f7b4dc2e1e9",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eef34b0e-0d80-4a1b-89ee-2c9a4a69045a",
                            TwoFactorEnabled = false,
                            Ho = "Kieu Dang",
                            IsVIP = false,
                            MaKH = "KH002",
                            NgaySinh = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0554513222",
                            Ten = "Thang"
                        },
                        new
                        {
                            Id = "86263342-cde4-4dc1-9546-a0e986ff6fca",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3fb38c68-c3e8-4668-83cc-e9afbbd70baa",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d951c9b4-13f5-4f91-9e1d-28f300fc2060",
                            TwoFactorEnabled = false,
                            Ho = "Nguyen Chung",
                            IsVIP = true,
                            MaKH = "KH003",
                            NgaySinh = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "09999999",
                            Ten = "Dung"
                        },
                        new
                        {
                            Id = "32467893-6e81-4077-99cd-ed17da38c487",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0c470922-0645-4b1e-bc15-62a6d970d231",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bfc73706-c647-486a-b618-ec90df501fc2",
                            TwoFactorEnabled = false,
                            Ho = "Ngo Ba",
                            IsVIP = false,
                            MaKH = "KH004",
                            NgaySinh = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "065332255",
                            Ten = "Duc"
                        },
                        new
                        {
                            Id = "56874680-cda1-4ddf-9dbd-5a7cb1c48abe",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "649a206e-2070-493c-8f97-d17457c727c6",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "98bdb96c-3113-439a-94ff-f28f4494b1d3",
                            TwoFactorEnabled = false,
                            Ho = "Ngo Ba",
                            IsVIP = false,
                            MaKH = "KH005",
                            NgaySinh = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0977470999",
                            Ten = "Nam"
                        });
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.NhanVien", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("CMT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiaChiId")
                        .HasColumnName("NhanVien_DiaChiId")
                        .HasColumnType("int");

                    b.Property<string>("Ho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("DiaChiId");

                    b.HasDiscriminator().HasValue("NhanVien");

                    b.HasData(
                        new
                        {
                            Id = "245d8f1e-0da8-45c8-8ced-b9777dc4a636",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "140301db-e7ca-4875-90bd-e69ea64af325",
                            Email = "huynguyen98.clc@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eef7d7be-2329-4d32-be79-00700cddd1f0",
                            TwoFactorEnabled = false,
                            CMT = "142829244",
                            DiaChiChiTiet = "10N01 - khu tai dinh cu",
                            Ho = "Nguyen Van",
                            LoaiNV = "phucvu",
                            Luong = 10000000m,
                            MaNV = "NV001",
                            NgaySinh = new DateTime(1998, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0977470992",
                            Ten = "Huy"
                        },
                        new
                        {
                            Id = "49ece4d1-a16d-45dd-aec2-23b3a85520ca",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05b7219b-6bed-46b0-aa84-0792b8f52d64",
                            Email = "hung@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ff3b3113-0f6d-401d-8256-a78b7d3e07ac",
                            TwoFactorEnabled = false,
                            CMT = "123456789",
                            DiaChiChiTiet = "khu tai dinh cu",
                            Ho = "Nguyen Van",
                            LoaiNV = "phucvu",
                            Luong = 9000000m,
                            MaNV = "NV002",
                            NgaySinh = new DateTime(1998, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "099457645",
                            Ten = "Hung"
                        },
                        new
                        {
                            Id = "54a5a4b3-a75a-441f-9b4b-d72965ac2b8d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a260458-1f37-42a5-9aec-099ed0e4caa9",
                            Email = "duc@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4ca61d8a-01ff-498c-b6d8-92897a2e4c94",
                            TwoFactorEnabled = false,
                            CMT = "115487982",
                            DiaChiChiTiet = "khu tai dinh cu",
                            Ho = "Nguyen Minh",
                            LoaiNV = "phucvu",
                            Luong = 9000000m,
                            MaNV = "NV003",
                            NgaySinh = new DateTime(1998, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "031231232",
                            Ten = "Duc"
                        },
                        new
                        {
                            Id = "cde4d308-0195-4125-877b-d7348ef5c887",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7f18d626-e9be-46a3-a769-83a0d6bb3fcb",
                            Email = "thang@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "554b1c41-7602-4612-be1f-760c46ad03b3",
                            TwoFactorEnabled = false,
                            CMT = "465487982",
                            DiaChiChiTiet = "khu tai dinh cu",
                            Ho = "Nguyen Minh",
                            LoaiNV = "phucvu",
                            Luong = 9000000m,
                            MaNV = "NV004",
                            NgaySinh = new DateTime(1998, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "031231232",
                            Ten = "Thang"
                        },
                        new
                        {
                            Id = "5a847a71-439b-4562-8972-f100fd106dc1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ff8b99cc-ddb6-41fb-ac9b-d151ba09ec02",
                            Email = "lannp@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a96fe15f-e527-4f17-a0dc-bde5f90545d9",
                            TwoFactorEnabled = false,
                            CMT = "213123123",
                            DiaChiChiTiet = "khu tai dinh cu",
                            Ho = "Ngo Phuong",
                            LoaiNV = "phucvu",
                            Luong = 9000000m,
                            MaNV = "NV005",
                            NgaySinh = new DateTime(1998, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0989456122",
                            Ten = "Lan"
                        });
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.BookPhongOrder", b =>
                {
                    b.HasOne("KaraokePayment.Data.Entity.KhachHang", "KhachHang")
                        .WithMany("BookPhongOrder")
                        .HasForeignKey("KhachHangId");

                    b.HasOne("KaraokePayment.Data.Entity.NhanVienCaLV", "NhanVienCaLV")
                        .WithMany("BookPhongOrder")
                        .HasForeignKey("NhanVienCaLVId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.BookPhongOrderPhong", b =>
                {
                    b.HasOne("KaraokePayment.Data.Entity.BookPhongOrder", "BookPhongOrder")
                        .WithMany()
                        .HasForeignKey("BookPhongOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KaraokePayment.Data.Entity.Phong", "Phong")
                        .WithMany("BookphjoBookPhongOrderPhong")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.NhanVienCaLV", b =>
                {
                    b.HasOne("KaraokePayment.Data.Entity.CaLV", "CaLv")
                        .WithMany("NhanVienCaLv")
                        .HasForeignKey("CaLvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KaraokePayment.Data.Entity.NhanVien", "NhanVien")
                        .WithMany("NhanVienCaLv")
                        .HasForeignKey("NhanVienId");
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.ThemHangHoa", b =>
                {
                    b.HasOne("KaraokePayment.Data.Entity.BookPhongOrderPhong", "BookPhongOrderPhong")
                        .WithMany("ThemHangHoa")
                        .HasForeignKey("BookPhongOrderPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KaraokePayment.Data.Entity.HangHoa", "HangHoa")
                        .WithMany("ThemHangHoa")
                        .HasForeignKey("HangHoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.KhachHang", b =>
                {
                    b.HasOne("KaraokePayment.Data.Entity.DiaChi", "DiaChi")
                        .WithMany()
                        .HasForeignKey("DiaChiId");
                });

            modelBuilder.Entity("KaraokePayment.Data.Entity.NhanVien", b =>
                {
                    b.HasOne("KaraokePayment.Data.Entity.DiaChi", "DiaChi")
                        .WithMany()
                        .HasForeignKey("DiaChiId");
                });
#pragma warning restore 612, 618
        }
    }
}
